config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

# Defines the root path route ("/")
# on the left side of the # is the controller name and on the right side is
the hash name is the action name also use the underscore version of it
    root "blog_post#home"
    get "/AboutMe", to: "about_me#index", as: "about_me"
    get "/BlogPost/new", to: "blog_post#new", as: "new"
    get "/BlogPosts", to: "blog_post#index"
    post "/BlogPosts", to: "blog_post#create", as: "blog_posts"
    get "/BlogPost/:id", to: "blog_post#show", as: "blog_post"
    delete "/BlogPost/:id", to: "blog_post#delete"
    patch "/BlogPost/:id", to: "blog_post#update"
    get "/BlogPost/:id/edit", to: "blog_post#edit", as: "blog_post_edit"
  # line 22 is taking in an argument within the path



  # resources :blog_post, only: [ :index, :show ]
  # Within the routes file I can have different types of verbs that has different actions: is to express intent
  # get(go get me some data), post(I want to create a resource), put/patch(update/change a resource), delete(delete a resource)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validate :custom_validator
  def custom_validator
    if body == title
      errors.add(:title, "They can not be the same!")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  # Applicaiton controller is an action controller.
  # It handles the incoming requests from a user and processes the necessary logic based on the request and then decides which view to render or data to return.

  def index
    @about_me
  end

  def home
    @blog_post = BlogPost.all
    render :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
# allow_browser versions: :modern
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
  # Applicaiton controller is an action controller.
  # It handles the incoming requests from a user and processes the necessary logic based on the request and then decides which view to render or data to return.
  before_action :set_blog_post, only: [ :show, :edit, :update, :delete ]
  before_action :set_all_blog_post, only: [ :index, :home ]

  def index
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    create_params = params.require(:blog_post).permit(:title, :body)
    @blog_post = BlogPost.new(create_params)
    if @blog_post.save
      redirect_to blog_post_path(@blog_post)
    else
      render :new
    end
  end

  def delete
    @blog_post.destroy
    redirect_to blog_posts_path
  end

  def update
      update_params = params.require(:blog_post).permit(:title, :body)
      if @blog_post.update(update_params)
        redirect_to blog_post_path(@blog_post)
      else
        render :edit
      end
    end

  def home
      render :index
      # It's rendering the same template as the index method therefore I wont have to create another html.erb template for it
    end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue
    redirect_to root_path
    # the rescue exception is there to "redirect" the error and instead of getting an error message that wont be able to find a post it redirects to the root_path/ home page
  end

  def set_all_blog_post
    @blog_post = BlogPost.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about_me/index.html.erb
<h1>About me Page</h1>
<h2>This page is about me, duh!<h2>
    <%= link_to "Home", root_path, class: "relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0 relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400" %>

app/views/blog_post/_form.html.erb
<%= form_with model: @blog_post, data: {turbo: false} do |form| %>
<div>
  <%= form.label :title %>
  <%= form.text_field :title, class: "border border-gray-500" %>
</div>

<div>
  <% @blog_post.errors[:title].each do |e| %>
  <p>
    <%= e.inspect%>
  </p>
  <%end%>
</div>

<div>
  <%= form.label :body %>
  <%= form.text_field :body, class: "border border-gray-500 " %>
</div>

<div>
  <% @blog_post.errors[:body].each do |e| %>
  <p>
    <%= e.inspect%>
  </p>
  <%end%>
</div>

<%= form.button class: "text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>

<% end %>

app/views/blog_post/edit.html.erb
<h1>Edit</h1>
<%= render partial: "form" %>

app/views/blog_post/index.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

    <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>

      </button>
      <!-- Dropdown menu -->
      <%
=begin%>
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Earnings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
          </li>
        </ul>
      </div>
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
        </svg>
      </button>
      <%
=end%>
    </div>
    <div class="items-center justify-between w-full flex w-auto order-1" id="navbar-user">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <%
=begin%>
        <li>
          <a href="#" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">
            <%= link_to "Home", root_path%>
        </li>
        <%
=end%>
        <li>
          <a class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
            <%= link_to "About Me", about_me_path %>
        </li>
        <li>
          <a class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
            <%= link_to "New Blog post", new_path%>
        </li>
        <li>
          <a class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
            <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>


<% @blog_post.each do |blog_post|%>
<!-- this is an erb tag that combines html and rails-->
<div>
  <h2><%= link_to blog_post.title , blog_post_path(blog_post.id) %> </h2>
</div>
<% end %>

app/views/blog_post/new.html.erb
<h1>New post </h1>
<%= render partial: "form" %>
<%= link_to "Home", root_path, class: "relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0 relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400" %>

app/views/blog_post/show.html.erb
<div>
  <h1>
    <%= @blog_post.title %>
    <%= @blog_post.body %>
  </h1>
</div>

<div>
  <%= button_to "Delete", blog_post_path(@blog_post), method: :delete, data: {turbo_method: :delete}, class: "text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
  <%= link_to "Edit", blog_post_edit_path(@blog_post), class: "relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-teal-300 to-lime-300 group-hover:from-teal-300 group-hover:to-lime-300 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-lime-800 relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0" %>
  <%= link_to "Home", root_path, class: "relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0 relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= content_for(:title) || "Blog" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<main class=" container mx-auto mt-28 px-5">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div>
    <% if user_signed_in? %>
    <%= link_to "Profile", edit_user_registration_path%>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete%>
    <% else %>
    <%= link_to "Login", new_user_session_path%>

    <% end %>
  </div>

  <%= yield %>
</main>
</body>

</html>